name: Build Maven Project

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (default: Java 21, update as needed)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install
